title: Website of Lauren Walker
baseURL: https://laurenjwalker.com
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 4
googleAnalytics: 'G-MXX9VBMBNW'
enableRobotsTXT: yes
ignoreFiles:
    -'\.ai$'
languages:
  en:
    contentDir: content
    title: Lauren Walker, PhD
    weight: 1
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  ananke_socials:
    - name: twitter
      url: https://twitter.com/Lrn_Walker
    - name: linkedin
      url: https://www.linkedin.com/in/lauren-walker-phd-68955041/
    - name: github
      url: https://github.com/LrnWalker

      
  author: ''
  background_color_class: bg-gold #used to be bg-black
  description: Axon guidance and synapse formation during development and regeneration
  favicon: ''
  #recent_posts_number: 3
  site_logo: ''
  text_color: 'black'
  header:
    -image:'/images/Header.jpg'

